### PR TITLE
Add pure Javascript guide

### PR DESCRIPTION
**Pull request by uriannrima**
Add a section in guides showing how to use Type-Route with plain JavaScript with an CodeSandbox example.

### CODE REVIEW

**Comment by bradenhs** [comment]
Thanks for the PR! I've been considering putting more explicit React support into Type Route (see https://github.com/typehero/type-route/pull/39) and the example in this guide looks very React-like to me. I'm curious, are you using Type Route with React or plain JavaScript? Do you have any thoughts on the referenced PR and the direction it would take the library?

**Comment by uriannrima** [comment]
I really used a "React-like" way of dealing with the interface because React seems like a more acceptable (and more status-quo) framework for doing such thing. But in reality I'm started doing this "plain javascript" example because I was hoping to use TypeRoute with an project that would use web components (like stencil, but without its router).

So, even though having an more "tight" integration with frameworks seems nice (to those who are working with) and more productive, I really don't see much value on doing it inside of the library itself, since most of users already uses the "built-in" router option (react-router, vue-router, etc). I mean, it definitely would be welcome to some people, but don't know how many would like it, you see?

A thing that I must say is that, I really though that it would be more difficult to make something using the TypeRouter lib, but when doing the example, oh boy, I was far from right. It is really simple. I think that the example for React using hooks already does a good job, maybe export some pre-build hooks to make things more smooth, and maybe wait for Vue 3 to be finally released to make some in the composition API. Otherwise, I really think that the lib is great as it is right now. (:

**Comment by uriannrima** [comment]
By the way, don't know why the PR Environment is using the React solution, when should be something like this one:

https://codesandbox.io/s/sweet-bartik-jc913?fontsize=14&hidenavigation=1&theme=dark

Maybe I did something wrong.

**Comment by bradenhs** [comment]
Thanks for the input @uriannrima! I've gone ahead and released Type Route `0.5.0` (the changes in #39). This means by default `type-route` has better React integration (hooks provided etc.). But you can still use Type Route without React by importing from `type-route/core`. There were a ton of doc changes needed to make this possible and unfortunately those kinda conflicted with this PR. Sorry about that! The timing was unfortunate :) If you have any thoughts though on how this page: https://typehero.org/type-route/docs/guides/type-route-without-react could be improved that'd be much appreciated. It seems to accomplish what this PR was doing but with the recent changes (literally just released) Type Route changes considered.

**Comment by bradenhs** [comment]
Going to go ahead and close this. Really appreciate the PR though @uriannrima!

**Pull request closed without merging**
