### PR TITLE
Type Route Next

### PR DESCRIPTION
**Pull request by bradenhs**
# Type Route Next 🚀

Type Route is just over one year old! Tons of great feedback has been given over the course of this last year. Some of that feedback has resulted in immediate changes to Type Route. Other comments though, needed to be more carefully considered since addressing them properly would influence the Type Route API in a breaking way. Type Route is used in production so, though not yet at version 1.0, being mindful of significant changes is still important.

After months of thinking about how to address these pieces of feedback in an elegant way, the time for action has finally come! Published under the `@next` tag is the upcoming version of Type Route. Outlined below is a list of significant changes that have been made. Please `npm install type-route@next` today and comment here with any feedback.

### String parameter definitions replaced with a more flexible and powerful `param.*` object

Previously you would do something like the following when creating a router:

```ts
import { createRouter, defineRoute } from "type-route";

const { routes } = createRouter({
  home: defineRoute("/"),
  user: defineRoute(
    {
      userId: "path.param.string",
    },
    (x) => `/users/${x.userId}`
  ),
  userList: defineRoute(
    {
      page: "query.param.optional.number",
    },
    () => `/users`
  ),
});
```

With `type-route@next` the above would instead look something like this:

```ts
import { createRouter, defineRoute, param } from "type-route";

const { routes } = createRouter({
  home: defineRoute("/"),
  user: defineRoute(
    {
      userId: param.path.string,
    },
    (x) => `/users/${x.userId}`
  ),
  userList: defineRoute(
    {
      page: param.query.optional.default(1),
    },
    () => `/users`
  ),
});
```

Making the parameter definitions object based instead of string based expands the API but also makes it possible to give optional parameters default values and even provide a custom serializer for a parameter's value as in this example:

```ts
import {
  createRouter,
  defineRoute,
  param,
  ValueSerializer,
  noMatch,
} from "type-route";

const userName: ValueSerializer<{ firstName: string; lastName: string }> = {
  parse: (raw) => {
    const [firstName, lastName, ...rest] = raw.split("-");
    if (!firstName || !lastName || rest.length > 0) {
      return noMatch;
    }
    return { firstName, lastName };
  },
  toString: (value) => `${value.firstName}-${value.lastName}`,
};

const { routes } = createRouter({
  user: defineRoute(
    {
      userName: param.path.ofType(userName),
    },
    (x) => `/user-${x.userName}`
  ),
});
```

You can also use `ofType<T>()` only passing in the type parameter without a `ValueSerializer<T>` object. In that case Type Route will use the default JSON value serializer whose implementation looks like this:

```ts
import { ValueSerializer, noMatch } from "type-route";

const valueSerializer: ValueSerializer<TValue> = {
  parse: (raw) => {
    let value: TValue;

    try {
      value = JSON.parse(raw);
    } catch {
      return noMatch;
    }

    return value;
  },
  stringify: (value) => JSON.stringify(value),
};
```

### Path parameter placement more flexible

Previously path parameters were constrained to be the only item in a particular path segment (a path segment being the characters between two forward slashes). So this `/user/${x.userId}/settings` was ok but this `/user-${x.userId}-settings` was not. Now both are supported. You still cannot include more than one path parameter per segment of the path but can achieve the functionality you're looking for there with a custom value serializer.

### Adds trailing path parameters

There has been no first class support for catch all routes in Type Route to date. It was possible to hack around this limitation by doing some custom parsing of the url if no route was matched before falling back to a not found page. With the introduction of trailing path parameters, however, there is now support for this. Unlike other path parameters a trailing path parameter is not url encoded by default and so can be given characters such as forward slashes. A trailing path parameter must be the last one in the path.

### Adds optional path parameters

Previously path parameters could not be optional. Now you can have up to one optional path parameter if it is the last in your path and has no leading or trailing text around the parameter within its path segment. Example:

```ts
defineRoute(
  {
    name: param.path.string,
    version: param.path.optional.string,
  },
  (x) => `/software/${x.name}/${x.version}`
);
```

### Adds state parameters

The history api exposes a way to pass along values embedded in state parameters as part of navigation (see https://developer.mozilla.org/en-US/docs/Web/API/History/state). Previously Type Route used this api internally but did not expose it for external use. Now declaring route parameters that reside in this state object is possible via the `param.state.*` object. Note that while this parameter definition has the same semantics as the others for consistency (required by default) its likely that you would want state parameters to be optional in most cases (`param.state.optional.*`) since simply copying/pasting a url would not pick up this special state object and therefore make that route unaccessible unless navigated to via application code or browser history.

### Custom query string serializer support

Type Route now supports a pluggable query string serializer. Since parameters definitions take care of doing serialization of a parameter's value the query string serializer is only responsible for matching up keys with their values. The default query string serializer implementation looks like this:

```ts
export const defaultQueryStringSerializer: QueryStringSerializer = {
  parse: (raw) => {
    const queryParams: Record<string, string> = {};

    for (const part of raw.split("&")) {
      const [rawParamName, rawParamValue, ...rest] = part.split("=");

      if (
        rawParamName === undefined ||
        rawParamValue === undefined ||
        rest.length > 0
      ) {
        continue;
      }

      queryParams[decodeURIComponent(rawParamName)] = rawParamValue;
    }

    return queryParams;
  },

  stringify: (queryParams) => {
    return Object.keys(queryParams)
      .map((name) => `${encodeURIComponent(name)}=${queryParams[name]}`)
      .join("&");
  },
};
```

It would be possible to support query strings that have alternate ways of representing array. For example `?letters[]=a&letters[]=b` could be parsed properly into `{letters:["a","b"]}` using a combination of a custom query string serializer and a custom value type serializer for the parameter. This value can be passed in when the router is created in the second options argument like this:

```ts
import { createRouter, defineRoute } from "type-route";

const { routes } = createRouter(
  {
    home: defineRoute("/"),
  },
  {
    queryStringSerializer: ...,
  }
);
```

### More permissive route matching

Previously any extraneous query string parameters would cause the route to not be a match. Now extraneous query and state parameters are allowed.

### Integration test suite

To establish a little more confidence in the project since the code changes are quite extensive [playwright](https://github.com/microsoft/playwright) was added to help with some integration tests. This test suite needs to be filled out a little more but the plumbing is all there.

### Fixes TypeScript "Go to definition"

Executing "Go to definition" on route names has always worked as expected but doing so on parameter names previously did not work. The TypeScript types have been adjusted to enable this behavior for parameter names as well as route names.

### Better display of TypeScript types on hover

Hovering over parameters on the route object would previously show a long and confusing TypeScript type. Now hovering over those should display a much more readable type definition free from all of the internal Type Route stuff.

### Adds lock to ensure only one navigation may be processed at a time

Previously if you had an asynchronous navigation handler that had conditions in it which affected how soon it resolved to a value you could end up in a situation where calls to push/replace would finish out of order. This could cause unexpected behavior in some edge case scenarios. Now a call to push/replace while a navigation is being processed will wait until the navigation handler resolves before being processed.

### Renames "history" to "session" and revamps API

Several changes have been made in this area:

- Access to internal history object no longer given
- history renamed to session to avoid conflicting the with global namespace history object
- `getCurrentRoute()` replaced with `getInitialRoute()` in an effort to steer users towards the best practice of using `listen` to sync route updates to their application.
- The `session` object is now of this type:

```ts
export type RouterSessionHistory = {
  push(url: string, state?: any): Promise<boolean>;
  replace(url: string, state?: any): Promise<boolean>;
  getInitialRoute(): Route;
  back(amount?: number): void;
  forward(amount?: number): void;
  reset(options: RouterSessionHistoryOptions): void;
};
```

## To Dos

Before merging and releasing this the following things should still be done:

- [x] Update documentation
- [x] Fill out integration test suite / resolve flakiness of tests
- [x] Add linter

## Future

Not all feedback is planned to be addressed in this PR. There just happened to be a bunch of closely related items that made sense to look at together. Items that are on the roadmap but won't be part of the initial release of the updated version of Type Route include:

- ~Hash router to support older browsers~ This will be part of the next release!
- Hash parameters

---

**Addresses** #33 #30 #29 #24 #23

### CODE REVIEW

**Comment by seivan** [comment]
A suggestion, instead of a runtime error when ending a path with `"/"`, why not simply remove it and do a console warn in dev?

**Comment by seivan** [comment]
I think I found a bug. 
https://codesandbox.io/s/weathered-fog-71h08?file=/src/playground.tsx

Right of the bat, it's hard to create a route that has params that are required together.
Something like 
```ts
 { userId: typeof param.query.string, userType: typeof param.query.string} |
 { accessId: typeof param.query.number, accessType: typeof param.query.number}
```

I tried these
```
  maybe: defineRoute(
   { userId: typeof param.query.string, userType: typeof param.query.string}
   | { accessId: typeof param.query.number, accessType: typeof param.query.number}
    ,
    () => `/maybe`
  )
```
and

```
  maybe: defineRoute(
   { maybe: 
           { userId: typeof param.query.string, userType: typeof param.query.string}
           | { accessId: typeof param.query.number, accessType: typeof param.query.number}
     }
    ,
    () => `/maybe`
  )
```

But no good, what actually worked was this, but it feels unnecessary to make a type for it, hoping it could be done inline. 
```
type MaybeRoute =
  | { userId: typeof param.query.string, userType: typeof param.query.string}
  | { accessId: typeof param.query.number, accessType: typeof param.query.number};

  maybe: defineRoute(
    {
      maybe: param.query.ofType<MaybeRoute>()
    },
    () => `/maybe`
  )
```

And it also requires you to "hard" cast
//Removed the other keys for brevity. 

```ts

       <a  {...routes.maybe.link({
          maybe: ({ userId: "23" } as any) as MaybeRoute
        })}
      >
        maybeRouteUserId
      </a>

      <a
        {...routes.maybe.link({
          maybe: ({ accessId: "99" } as any) as MaybeRoute
        })}
      >
        maybeRouteAccessID
      </a>
```

I think the `ValueSerializer` approach is messy and too low level. There needs to be a far more abstracted and high level (less verbose) way of adding custom paths & params. 
Are you ok with tweaking a few things from a API PoV?

**Comment by seivan** [comment]
@bradenhs Thanks for the speedy response. You were correct, that makes sure I don't have to force/hard cast, but the initial issue still remains.
Not to mention that how would one make the distinction between `paths` and `params or even defining optionals with defaults? 

The good news is, this is actually pretty neat to do inline. 
```ts
  maybe: defineRoute(
    {
      maybe: param.query.ofType<{ userId: string } | { accessId: string }>()
    },
    () => `/maybe`
  )
```

The bad news are, 

1. It requires a  key (`maybe`) prefix to wrap those values, 
2. The url ends up looking like  `/maybe?maybe=%7B%22userId%22%3A%2223%22%7D` I assume because it uses that default json parser. 
3. No ability to define default values or options
4. Optional path arguments will be `/undefined/`
Even tried setting this 
```ts
 organizationUsers: defineRoute(
    { organizationId: param.path.string, userId: param.path.optional.string }
    ,
    (p: {userId?: string, organizationId: string}) => { 
      const postPath = (p.userId !== undefined ? `/users/${p.userId}` : "/users")
      return `/organizations/${p.organizationId}` + postPath
    }
  ),
```

**Comment by seivan** [comment]
I went ahead and tested 
```ts
  software: defineRoute(
    {
      name: param.path.string,
      version: param.path.optional.string,
    },
    (x) => `/software/${x.name}/${x.version}`
  ),
```
And as before the url ends up being  `/software/12/undefined`

**Comment by bradenhs** [comment]
Great feedback @seivan! Its very appreciated. Here's a more detailed reply:

> I think the ValueSerializer approach is messy and too low level. There needs to be a far more abstracted and high level (less verbose) way of adding custom paths & params. Are you ok with tweaking a few things from a API PoV?

I'm absolutely ok with tweaking things from an API PoV! I agree that the `ofType` api can be hard to deal with. I was thinking of providing a few common `ValueSerializer` objects either as part of this package or a separate package. So a user could do something like this:

```ts
import { defineRoute } from "type-route"
import { stringArray } from "type-route-value-serializers";

defineRoute(
  {
    // stringArray creates nicer urls like this: ["hello","there"] => "/?custom=hello,there"
    custom: param.query.ofType(stringArray)
  },
 () => "/"
);
```

Then if a use case was especially complex they'd still be able to accomplish it by writing their own `ValueSerializer` when one of the provided ones does not satisfy. I even thought about adding a value serializer factor that would take an io-ts type so we could have real runtime checking of the value as opposed to compile time. I'm hesitant about including that in the main package though.

> A suggestion, instead of a runtime error when ending a path with "/", why not simply remove it and do a console warn in dev?

That's good suggestion. I'm not sure if I'd want to log a warning to the console but I would be open to making the path creation more permissive in the way you suggest with a note in the documentation about that behavior. Need to think on it some more.

> It requires a key (maybe) prefix to wrap those values,

I agree with you that that could be annoying but I'm having a hard time imaging a good way to get around that from an api perspective.

> The url ends up looking like /maybe?maybe=%7B%22userId%22%3A%2223%22%7D I assume because it uses that default json parser.

Yes. Some characters such as "&" and "/" if included in the value you provided could cause issue in the url. To avoid those Type Route url encodes path and query parameters by default. With the `ofType` function you can provide a serializer that turns url encoding off if you want though.

> No ability to define default values or options going with approach mentioned above.

Could you explain this point in a little more detail? Not sure I fully understand.

> Optional paths will be /undefined/ in the url

Great catch! I've fixed this issue and added a test. The two main things (barring any significant changes in the api) that need to be done before releasing this is updating the documentation and improving upon the test suite. The former is especially important given the significant code changes in this branch. I want to make sure the code is rock solid before releasing this.

**Comment by seivan** [comment]
@bradenhs Thanks for fixing that, appreciate it. 

> I'm absolutely ok with tweaking things from an API PoV! I agree that the ofType api can be hard to deal with. I was thinking of providing a few common ValueSerializer objects either as part of this package or a separate package. So a user could do something like this:


I phrased that incredibly poorly. I am so sorry, what I meant to say is that it's pretty good, and it's nice to have a neat way of making your own serializer as an escape hatch, so one could for instance do slug type URLs by passing in an object and extract `id` and `title`. The way I **should** have phrased it, is that there should be more options out of the box that wouldn't need that escape hatch because it's quite verbose and can be annoying to repeat for multiple projects. 

I hope that wasn't too annoying. 

> That's good suggestion. I'm not sure if I'd want to log a warning to the console but I would be open to making the path creation more permissive in the way you suggest with a note in the documentation about that behavior. Need to think on it some more.

Yeah the reason I added logging was because it might mess with the users head if they have certain expectations and the library cuts that off, could be documented and that would make logging redundant. 


> No ability to define default values or options going with approach mentioned above.

I was wrong, this was just a bug that you just fixed.

**Comment by bradenhs** [comment]
> I hope that wasn't too annoying.

Not all all! I just value the input :) Keep it coming!

> there should be more options out of the box that wouldn't need that escape hatch

Excellent point. Solving for your example with the `maybe` route in a generic way seems difficult without resorting to a custom serializer but one common pattern Type Route could do a better job supporting out of the box is arrays. I agree url encoded stringified json doesn't make for a very nice url. Customer serializers are the best way I can think of to help with that for objects but for arrays I think Type Route could do a better job helping out. For what its worth, that `maybe` route with a custom serializer could look like this:

```ts
  defineRoute(
      {
        id: param.query.ofType<{ user: string } | { access: string }>({
          parse: (raw) => {
            if (raw.startsWith("user-")) {
              return { user: raw.slice("user-".length) };
            } else if (raw.startsWith("access-")) {
              return { access: raw.slice("access-".length) };
            } else {
              return noMatch;
            }
          },
          stringify: (value) => {
            if ("user" in value) {
              return `user-${value.user}`;
            } else {
              return `access-${value.access}`;
            }
          },
        }),
      },
      () => `/maybe`
    )
```

I agree its not great to have to specify all that custom logic but I can't think of a good way around it. I'd love to hear any thoughts you have on ways to go about that though. Here are the changes I made to support arrays:

- Introduction of the `array` modifier for parameter definitions. Now any parameter can include `array` in its chain like this: `param.query.array.number` or `param.query.optional.array.ofType<{ something: string }>().default([{ something: "hi" }])`
- Introduction of the `boolean` type for parameter definitions. Usage would be like this `param.query.boolean`.
- When creating a router the second argument is the optional router options object. That has been expanded to include a new `arrayFormat` property used to configure how Type Route serializes arrays in the url. Usage example:

```ts
const { routes, listen, session } = createRouter(
  { ... },
  {
    arrayFormat: {
      queryString: "singleKeyWithBracket",
      separator: ","
    },
  }
);
```

The options given above are the defaults and would result in arrays represented like this in the url: `?someArray[]=1,2,3`. The other options are as follows:

`singleKey` => `?someArray=1,2,3`
`multiKey` => `?someArray=1&someArray=2&someArray=3`
`multiKeyWithBracket` => `?someArray[]=1&someArray[]=2&someArray[]=3`

Any input or clarifications on the expansion of the api as described above would be great! The latest playground link posted should have a working example of the updates.

**Comment by bradenhs** [comment]
Depending on the exact use case the other potential solution to the `maybe` route example you've given is to have two routes with the same path but different query parameters:

```ts
import { createRouter, defineRoute, param, createGroup } from "type-route";

const { routes } = createRouter({
  userId: defineRoute(
    {
      userId: param.query.string
    },
    () => `/maybe`
  ),
  accessId: defineRoute(
    {
      accessId: param.query.string
    },
    () => `/maybe`
  )
});

const maybeGroup = createGroup([routes.userId, routes.accessId]);
```

Along with using `createGroup` this could give a solution that is both ergonomic to work with and correct.

**Comment by seivan** [comment]
I am just writing this to clarify, I am not saying it's an issue or a problem. 


Assume these `routes`: 
```jsx
    userList: defineRoute(
      {},
      () => `/users`
    ),
    user: defineRoute(
      { userId: param.path.optional.string },
      (x) => `/users/${x.userId}`
    ),
```


Assume these `conditions`: 

```jsx
  if (route.name === routes.userList.name) {
   return. <div> UserList </div>
  if (route.name === routes.user.name) {
    return <div>User</div>;
  }
```


Assume this `link`
```jsx
      <a {...routes.user.link({} } >
        User
      </a>
```


It will end up on `userList` because the url will be `/users` since there is no `id` passed as a path. 
This makes total sense, and is accurate. 
The URL defines what route it is.
```jsx

   //Will fall here, 
  if (route.name === routes.userList.name) {
   return. <div> UserList </div>

  //And **NOT** here! 
  if (route.name === routes.user.name) {
    return <div>User</div>;
  }
```

However the gotcha here is that the link was defined as 

`<a {...routes.user.link({} } >` 

This seems like it's by design and I just wanted confirmation.

**Comment by seivan** [comment]
Your [approach](https://github.com/type-route/type-route/pull/35#issuecomment-619369733) discussed above is better but I am just curious why it doesn't work out of the box with union types today? 


What I am wondering is why is `id` necessary here? 
If we ignore the ugly URL for a second and go with 
```jsx
    maybe: defineRoute(
      {
        id: param.query.ofType<{ user: string } | { access: string }>(),
       }
      () => `/maybe`
    ),



      <a
        {...routes.maybe.link({
          id: {user: "usseerr"}
        })}
      >
        user
      </a>
      <a
        {...routes.maybe.link({
          id: {access: "accessss"}
        })}
      >
        access
      </a>
```


Why can't the initial object passed be `{ user: string } | { access: string }`? 

Also something like this for a union type is a bit too much and should preferably work out of the box since union types are part of TS.

```ts
        id: param.query.ofType<{ user: string } | { access: string }>({
          parse: (raw) => {
            console.log("PARSE")
            console.log(raw)
            if (raw.startsWith("user-")) {
              return { user: raw.slice("user-".length) };
            } else if (raw.startsWith("access-")) {
              return { access: raw.slice("access-".length) };
            } else {
              return noMatch;
            }
          },
          stringify: (value) => {
            console.log("stringify")
            console.log(value)
            if ("user" in value) {
              return `user-${value.user}`;
            } else {
              return `access-${value.access}`;
            }
          },
        })
```
It's simply too much and too much that can go wrong. 

It's easily solved by your [`createGroup`](https://github.com/type-route/type-route/pull/35#issuecomment-619369733) but it wouldn't the first take thinking in terms of TS union types, as in it wouldn't come natural. I wonder if there is an approach where union types would work out of the box as part of the first argument to `defineRoute`

**Comment by bradenhs** [comment]
I agree that it would be nice to have the flexibility of having those parameters be a base parameter on the route. Here's another possibility but it also isn't quite the same:

```ts
defineRoute(
  {
    userId: param.query.optional.string,
    accessId: param.query.optional.string
  }
  () => `/maybe`
),
```

In the above example you could erroneously provide both a `userId` and `accessId` or even neither and the route will still match the given url.  Those cases could be mitigated in user land code. So there are certainly a few viable workarounds for achieving this behavior. I'm still unsure though, of the best way to go about changing the api to make support for this slightly more complex use case more simple without further complicating the api for more common cases. If you have any concrete ideas about how the api could change I'd be really interested in hearing them!

**Comment by bradenhs** [comment]
Just added this new behavior: When a user changes routes the window (if they're in a browser environment) will automatically scroll to the top of the page. This does not occur when using a replace action. Its been my observation that scrolling to the top of the new page is almost always the desired behavior when navigating. This behavior can be disabled by passing `scrollToTop: false` as an option when creating the router.

**Comment by bradenhs** [comment]
Just pushed up some more big changes:

**Ready for Suspense**

In order to give the best support possible for React's upcoming concurrent mode there needed to be some changes to how Type Route does things. For instance the `useTransition` hook (or whatever it ends up being called in the end) relies on any calls to `setState` happening in the call hierarchy of its `startTransition` method. This signals to React that its okay to start on those updates on a different "branch" while still displaying the currently rendered component tree. The potentially asynchronous handlers you could pass to the listen function don't play well with this. This updates forces those handlers to be synchronous. You can still opt out of a navigation by returning false from the navigation handler. Its worth noting that all application triggered updates will call the listener function _before_ the url updates and all browser triggered updates will trigger the listener function _after_ the url updates. I don't imagine this being too much of an issue in practice especially given the synchronous nature of that function now. Other patterns made possible by React's new concurrent mode such as prefetching data motivated this next change.

**Addon API**

Go ahead and checkout the latest PR env to see this in action. Looking at how to support things like prefetching data in a more first class way with the router it became clear that the variety of needs and patterns out there would be difficult to accommodate well. The solution for this is router addons. Now you can provide addons to the router which add context aware functions to routes. Something like this should now be possible:

```tsx
import React, { useState } from "react";
import { createRouter, defineRoute, param, AddonContext } from "type-route"

const routeDefs = {
  blog: defineRoute("/blog"),
  post: defineRoute(
    { id: param.path.string },
    x => `/post/${x.id}`
  )
};

const { listen, routes, session }  = createRouter({
  routeDefs,
  addons: {
    preload,
    preloadLink
  }
});

function preload(ctx: AddonContext<typeof routeDefs>) {
  if (ctx.route.name === 'post') {
    // some code to preload post data
    preloadPost(ctx.route.params.id);
  }
}

function preloadLink(ctx: AddonContext<typeof routeDefs>) {
  return {
    ...ctx.link(ctx.route.params),
    onMouseDown: () => {
      // Ok they're likely to click this so start loading the context of the next page already
      preload(ctx);
    }
  }
}

function App() {
  const [route, setRoute] = useState(session.getInitialRoute());

  useEffect(() => listen(nextRoute => {
    nextRoute.addons.preload();
    setRoute(nextRoute))
  }, []);

  return <div>
    <a {...routes.post.addons.preloadLink({ id: 1 })>Post 1</a>
    ....
  </div>
}
```

Some of these new changes are pretty raw so any feedback would be great. Also that wasn't explained terribly well either so questions are welcome as well :)

**Comment by bradenhs** [comment]
Getting the proposed addon api mentioned here: https://github.com/typehero/type-route/pull/35#issuecomment-626092042 working nicely was proving to be a chore. Going down that direction did lead to changes with how routes are constructed even if an addon api did prove to be a dead end (at least for now). `Route` objects now contain everything that was previously on a `RouteDefinition`. `RouteDefinition` objects are now `RouteBuilder` functions. So instead of this `routes.user.link({ userId: "abc" })` you would do this `routes.user({ userId: "abc" }).link`. This adjustment made writing some helper functions around TypeScript's api slightly easier to create in user land.

Also after considering scroll restoration more closely I decided to keep that in user land since while Type Route does know when a navigation handler returns `false` that doesn't necessarily correspond to when the application renders a new route. When running React in concurrent mode a call to setState doesn't necessarily cause the application to render synchronously so it was fairly easy to have Type Route scroll the page to the top before that new page had rendered which resulted in weird behavior.

**Comment by bradenhs** [comment]
For anyone following along sorry for the noise. The PR env comments could be toned down a bit. Testing out updated docs on  a new domain necessitated lots of test type commits :( The good news is you can now see some work in progress docs for @next at https://typehero.org/type-route

**Pull request merged**
